url=jdbc:mysql://localhost:3306/opoppr
username: "${DB_USERNAME}"
password: "${DB_PASSWORD}"
driver=com.mysql.cj.jdbc.Driver
referenceUrl=hibernate:spring:com.opao.pp_api.features?dialect=org.hibernate.dialect.MySQLDialect
